### ISSUE TITLE
Allow n=6 example field to be written to classic netCDF-3

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfdm#140]
As observed in the unit test for append mode, #69, the seventh (index `6`) example field can't be written to `'NETCDF3_CLASSIC'` format due to having `int64` data, whereas the rest of the examples are writable to any of the supported netCDF formats:

```pycon
>>> import cfdm
>>> f = cfdm.example_field(6)
>>> # Writes fine to all of the other formats, e.g:
>>> cfdm.write(f, 'file-to-write-to.nc', fmt='NETCDF3_64BIT_DATA')
>>> cfdm.write(f, 'file-to-write-to.nc', fmt='NETCDF4')
>>> # ... just not NETCDF3_CLASSIC:
>>> cfdm.write(f, 'file-to-write-to.nc', fmt='NETCDF3_CLASSIC')
Traceback (most recent call last):
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2728, in _write_netcdf_variable
    self._createVariable(**kwargs)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2476, in _createVariable
    g["nc"][ncvar] = g["netcdf"].createVariable(**kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2771, in netCDF4._netCDF4.Dataset.createVariable
  File "src/netCDF4/_netCDF4.pyx", line 3822, in netCDF4._netCDF4.Variable.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1950, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
    nc_encodings = self._write_node_count(
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 1693, in _write_node_count
    self._write_netcdf_variable(ncvar, (geometry_dimension,), count)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2734, in _write_netcdf_variable
    raise ValueError(
ValueError: Can't write int64 data from <Count: (2) > to a NETCDF3_CLASSIC file. Consider using a netCDF4 format, or use the 'datatype' parameter, or change the datatype before writing.
```

So we said we would change it so it can be written to all such formats as with all other examples.

As a workaround for now for testing in #69 I added a skip at the relevant place in 15bd0d12f1347c97bc40d02032ab2b3aea992f7f.

**Comment by davidhassell** [comment]
Hi @sadielbartholomew  - I think we can close this now, as `examplefield.py` now uses `"i4"` for all of its integer datatypes. Please reopen if I've missed something ...

**Comment by sadielbartholomew** [comment]
Thanks @davidhassell, though if using the current and up-to-date `master` branch I comment out the skip I added to bypass the issue, I still see the error relating to attempted writing of `int64 data` to netcdf3 classic:

```pycon
======================================================================
ERROR: test_write_netcdf_mode (__main__.read_writeTest)
Test the `mode` parameter to `write`, notably append mode.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2729, in _write_netcdf_variable
    self._createVariable(**kwargs)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2462, in _createVariable
    g["nc"][ncvar] = g["netcdf"].createVariable(**kwargs)
  File "src/netCDF4/_netCDF4.pyx", line 2771, in netCDF4._netCDF4.Dataset.createVariable
  File "src/netCDF4/_netCDF4.pyx", line 3822, in netCDF4._netCDF4.Variable.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1950, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Not a valid data type or _FillValue type mismatch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_read_write.py", line 268, in test_write_netcdf_mode
    cfdm.write(ex_field, tmpfile, fmt=fmt, mode="a")
  File "/home/sadie/cfdm/cfdm/read_write/write.py", line 522, in write
    netcdf.write(
  File "/home/sadie/cfdm/cfdm/decorators.py", line 171, in verbose_override_wrapper
    return method_with_verbose_kwarg(*args, **kwargs)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 4834, in write
    return self._file_io_iteration(
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 5082, in _file_io_iteration
    self._write_field_or_domain(f)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 3655, in _write_field_or_domain
    coordinates = self._write_auxiliary_coordinate(
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2196, in _write_auxiliary_coordinate
    extra = self._write_bounds(f, coord, key, ncdimensions, ncvar)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 1299, in _write_bounds
    extra = self._write_node_coordinates(
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 1572, in _write_node_coordinates
    nc_encodings = self._write_node_count(
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 1680, in _write_node_count
    self._write_netcdf_variable(ncvar, (geometry_dimension,), count)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2739, in _write_netcdf_variable
    raise ValueError(
ValueError: Can't write int64 data from <Count: (2) > to a NETCDF3_CLASSIC file. Consider using a netCDF4 format, or use the 'datatype' parameter, or change the datatype before writing.
```

So the issue at hand remains, unless I have missed some thing myself. I'll reopen, but likewise please close again if I am wrong!

**Comment by sadielbartholomew** [comment]
I should also add there is the equivalent issue for cf-python that could for efficiency be addressed at the same time (though I only opened an issue here for `cfdm`, I'll create a stub Issue now and link it here), where the corresponding skip is, there:

https://github.com/NCAS-CMS/cf-python/blob/124ed7d78f4eb3ba988a40f784ebef20eb578312/cf/test/test_read_write.py#L347-L351

**Comment by davidhassell** [comment]
Hi Sadie, sorry - I should have checked rather than just looking at the code! There's nothing wrong with `examplefield.py`, which was all I'd looked at, rather it's the fact that the field has some geometry coordinates, which causes an integer `Count` variable to be made on the fly at write time:

https://github.com/NCAS-CMS/cfdm/blob/master/cfdm/read_write/netcdf/netcdfwrite.py#L1629-L1632.

We could just set `dtype='int32'` in the numpy calls in the above code, which would be OK in many cases I'm sure, but I can envisage quite large Counts, e.g. for counting the nodes of very detailed national borders.

There must be a good way of safely casting to int32 if the number are small enough ...

```python
        if self.implementation.get_data_ndim(bounds) == 2:
            array = numpy.ma.count(array, axis=1)
        else: 
            array = numpy.ma.count(array, axis=2).sum(axis=1)

        if <max of array can be represented by int32>:
            array = array.astype('int32')
``` 

If the Count variable still comes out as int64 after this, well it's too bad! We can put a note in the `write.py` docs that writing geometry coordinates in netCDF3 might cause problems if there are loads of nodes.

**Comment by sadielbartholomew** [comment]
Thanks for clarifying, David. Do you want to take this on, since you clearly have ideas about how to address it and perhaps have tried them out, and I should get going with Daskifying cf-python? If not, I am happy to investigate along the lines you have indicated.

**Comment by davidhassell** [comment]
Sure - I'll take this.
