### ISSUE TITLE
Tests: sed setup lines invalid on Mac OS

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cfdm#25]
As [detected by](https://github.com/NCAS-CMS/cfdm/runs/602126473?check_suite_focus=true) the "Run test suite" GH Actions workflow for the latest commit, ce9a5a4, a sub-test fails on Mac OS but not on a Linux (Ubuntu) OS in the setup stage on an in-place `sed` command:

```pytb
======================================================================
ERROR: test_read_CDL (test_read_write.read_writeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/runners/2.169.0/work/cfdm/cfdm/cfdm/test/test_read_write.py", line 216, in test_read_CDL
    shell=True, check=True)
  File "/Users/runner/miniconda3/envs/cfdm-latest/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'sed -i "1 i\ \ " /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp27bjmfaj.cfdm_test' returned non-zero exit status 1.
```
[This post](https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux) enlightens that Mac OS treats in-place `sed` commands slightly differently, requiring an extension to be specified.

It will be a quick fix that I will put in now, but raising an intermediate GH Issue as a note since it is likely we could run into this setup issue again.

**Comment by sadielbartholomew** [comment]
In fact, having a look now, there are multiple invalid lines to fix.

**Comment by sadielbartholomew** [comment]
Nope, a change which the post suggested would work did not (I have no Mac to test on & it is not worth the time to access our testing one via ``ssh``.) Trying again later...

**Comment by sadielbartholomew** [comment]
Wow, it is still not working after changing to try two alternative syntaxes tried and tested by multiple others in turn. Talk about a lesson in not making assumptions. I will have to use the ole testing Mac after all (tomorrow, when I have recovered the will to live).

**Comment by sadielbartholomew** [comment]
I've put a fix in that should work by avoiding ``sed -i`` & instead using a not in-place ``sed`` with an overwrite of the original file with the changed one, to save us from this portability headache altogether.

I can't see whether it has worked yet on the Actions env as Actions are down at the moment (GitHub issues). I'll check back later to manually trigger the run if necessary.

**Comment by sadielbartholomew** [comment]
Forgot to reopen this as it is not yet fixed! It got left behind as I did other things.

For now with an imminent release we have agreed to wrap the specific test with logic to not run it if on a Mac, as we are confident enough that the particular functionality there will work on Mac OS if it does on a Linux variant. So I will leave this open as going forward we want a portable version that is valid to run on both forms of OS.

**Comment by sadielbartholomew** [comment]
(Not a bug as such, it is just a test line in question.)
